name: Trigger auto deployment for container-app-nmxt5hktm7btm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-nmxt5hktm7btm-AutoDeployTrigger-0a06efaa-9ab2-49b5-838f-26ad76091b2e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNMXT5HKTM7BTM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNMXT5HKTM7BTM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNMXT5HKTM7BTM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPNMXT5HKTM7BTM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNMXT5HKTM7BTM_REGISTRY_PASSWORD }}
          containerAppName: container-app-nmxt5hktm7btm
          resourceGroup: todonodejspgsqlgoogleauthbad79021
          imageToBuild: default/container-app-nmxt5hktm7btm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


